ParamsNum_IGORtoPython_dict = {
    "HdrLenInValuePairs" : "HeaderLengthInValuePairs",
    "HdrLenInBytes"      : "Header_length_in_bytes",
    "MinVolts_AO"        : "MinVoltsAO",
    "MaxVolts_AO"        : "MaxVoltsAO",
    "StimChanMask"       : "StimulusChannelMask",
    "MaxStimBufMapLen"   : "MaxStimulusBufferMapLength",
    "NumberOfStimBufs"   : "NumberOfStimulusBuffers",
    "TargetedPixDur_us"  : "TargetedPixelDuration_µs",
    "MinVolts_AI"        : "MinVoltsAI", 
    "MaxVolts_AI"        : "MaxVoltsAI", 
    "InputChanMask"      : "InputChannelMask",
    "NumberOfInputChans" : "NumberOfInputChans",
    "PixSizeInBytes"     : "PixelSizeInBytes",
    "NumberOfPixBufsSet" : "NumberOfPixBufsSet",
    "PixelOffs"          : "PixelOffs",
    "PixBufCounter"      : "PixBufCounter",
    "User_ScanMode"      : "ScanMode",
    "User_dxPix"         : "FrameWidth",
    "User_dyPix"         : "FrameHeight",
    "User_nPixRetrace"   : "PixRetraceLen",
    "User_nXPixLineOffs" : "XPixLineOffs",
    "User_divFrameBufReq": "divFrameBufReq",
    "User_ScanType"      : "ScanType",
    "User_nSubPixOversamp":"NSubPixOversamp",
    "RealPixDur"         : "RealPixelDuration_µs",
    "OversampFactor"     : "Oversampling_Factor",
    "XCoord_um"          : "XCoord_um",
    "YCoord_um"          : "YCoord_um",
    "ZCoord_um"          : "ZCoord_um",
    "ZStep_um"           : "ZStep_um",
    "Zoom"               : "Zoom", 
    "Angle_deg"          : "Angle_deg", 
    "User_NFrPerStep"    : "NFrPerStep",
    "User_XOffset_V"     : "XOffset_V",
    "User_YOffset_V"     : "YOffset_V",
    "User_dzPix"         : "dZPixels",
    "User_nZPixLineOff"  : "ZPixLineOffs",
    "User_SetupID"       : "SetupID",
    "User_LaserWaveLen_nm":"LaserWavelength_nm",
    "User_aspectRatioFr" : "AspectRatioFrame",
    "User_stimBufPerFr"  : "StimBufPerFr",
    "User_nYPixLineOffs" : "YPixLineOffs",
    "User_iChFastScan"   : "iChFastScan",
    "User_noYScan"       : "noYScan",
    "User_dxFrDecoded"   : "dxFrDecoded",
    "User_dyFrDecoded"   : "dyFrDecoded",
    "User_dzFrDecoded"   : "dzFrDecoded",
    "User_trajDefVRange_V": "trajDefVRange_V",
    "User_nTrajParams"   : "nTrajParams",
    "User_trajParams_mask": "TrajParams_*",
    "User_zoomZ"         : "zoomFactorZ",
    "User_offsetZ_V"     : "offsetZ_V",
    "User_zeroZ_V"       : "zeroZ_V",
    "User_ETL_polarity_V"  : "ETL_polarity_V",
    "User_ETL_min_V"      : "ETL_min_V",
    "User_ETL_max_V"      : "ETL_max_V",
    "User_ETL_neutral_V"  : "ETL_neutral_V",
    "User_nImgPerFr"     : " nImgPerFr",
    "User_nWarpParams"   : "nWarpParams",
    "User_WarpParamsStr" : "WarpParamsStr",
    "User_dzFr"          : "dZPixels",
    ""                 : ""
}
ParamsNum_PythontoIGOR_dict = {v: k for k, v in ParamsNum_IGORtoPython_dict.items()}